### ISSUE TITLE
Rename "WrappedDefault" and "WrappedDefaultOptional"?

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/Foil#73]
Initially I struggled to come up with a good name here and I honestly don't like this name at all.

- No property wrappers use "wrapped" in the name. It's kinda lame, like writing `class NetworkManagerClass { }`.
- SwiftUI took `AppStorage`, so we can't use that.

Right now, I'm thinking `FoilStorage` and `FoilStorageOptional` ?

Open to ideas here.

**Comment by jessesquires** [comment]
cc @basememara @ejensen @JonnyBeeGod @nolanw in case any of you have opinions here! 😄

**Comment by nolanw** [comment]
I agree it's a clunky name. Though if I had no idea what Foil (the library) was and came across some property marked `WrappedDefault` that took a `key` parameter, I would confidently guess it's backed by `UserDefaults`. That seems useful.

I like keeping "default" in the name because one of the distinguishing characteristics of Foil is that it correctly registers defaults. And "foil" is a wrapping (and I think you did good choosing that name). So maybe `FoilDefault` and `FoilDefaultOptional`? Gives a hint that it's `UserDefaults` and also explains why `import Foil` is at the top of the file.

Or `FoilWrapped` and `FoilWrappedOptional`? Like "what's this wrapped in?" "Foil." But then you have to know that "Foil" means `UserDefaults` :)
